name: Unit Tests

on:
  push:
    branches:
      - 'dev-feature-testing'
  pull_request:
    branches: [dev-feature-testing]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          yarn add jest 
          yarn jest